#image:
#  file: .gitpod.Dockerfile

ports:
  - port: 7860
    onOpen: open-browser

tasks:
  - before: >
      echo "before init..."
  - init: |
      pip install -r requirements.txt
      bash <(wget -qO- https://raw.githubusercontent.com/AUTOMATIC1111/stable-diffusion-webui/master/webui.sh)
      sudo chmod +x webui.sh
  - command: ./webui.sh
  
